#ifndef CEA0B346_3A08_480F_B1BF_0803EFB1DD13
#define CEA0B346_3A08_480F_B1BF_0803EFB1DD13

#define DEFAULT_LAYER 0
#define DL DEFAULT_LAYER

#define CONTROL_LAYER 1
#define CL CONTROL_LAYER

#define MACHINE_CTRL_LAYER 2
#define ML MACHINE_CTRL_LAYER

#define REMOTE_DEFAULT_LAYER 3
#define RDL REMOTE_DEFAULT_LAYER

#define REMOTE_CTL_LAYER 4
#define RCL REMOTE_CTL_LAYER

#define REMOTE_MACHINE_CTL_LAYER 5
#define RML REMOTE_MACHINE_CTL_LAYER

#define MAC_DEFAULT_LAYER 6
#define MDL MAC_DEFAULT_LAYER

#define MAC_CTL_LAYER 7
#define MCL MAC_CTL_LAYER

#define MAC_MACHINE_CTL_LAYER 8
#define MML MAC_MACHINE_CTL_LAYER

#endif /* CEA0B346_3A08_480F_B1BF_0803EFB1DD13 */
